In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data=pd.read_csv('/content/suv_data.csv')

In [3]:
data

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   User ID          400 non-null    int64 
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64 
 3   EstimatedSalary  400 non-null    int64 
 4   Purchased        400 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 15.8+ KB


In [5]:
X = data.iloc[:, 1:-1].values
y = data.iloc[:, -1].values

In [6]:
X

array([['Male', 19, 19000],
       ['Male', 35, 20000],
       ['Female', 26, 43000],
       ...,
       ['Female', 50, 20000],
       ['Male', 36, 33000],
       ['Female', 49, 36000]], dtype=object)

In [8]:
y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,

In [9]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
X=X[:, 1:]

In [10]:
X

array([[1.0, 19, 19000],
       [1.0, 35, 20000],
       [0.0, 26, 43000],
       ...,
       [0.0, 50, 20000],
       [1.0, 36, 33000],
       [0.0, 49, 36000]], dtype=object)

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [12]:
X_train

array([[0.0, 29, 28000],
       [0.0, 45, 22000],
       [1.0, 46, 117000],
       [1.0, 32, 18000],
       [1.0, 22, 81000],
       [1.0, 25, 87000],
       [1.0, 48, 33000],
       [1.0, 35, 58000],
       [1.0, 47, 23000],
       [1.0, 26, 32000],
       [0.0, 32, 135000],
       [1.0, 60, 34000],
       [0.0, 52, 21000],
       [0.0, 38, 55000],
       [1.0, 25, 90000],
       [0.0, 58, 38000],
       [1.0, 49, 88000],
       [0.0, 37, 78000],
       [0.0, 35, 77000],
       [0.0, 34, 43000],
       [1.0, 20, 49000],
       [1.0, 46, 88000],
       [0.0, 31, 34000],
       [0.0, 47, 30000],
       [1.0, 35, 50000],
       [1.0, 39, 96000],
       [0.0, 33, 113000],
       [1.0, 49, 86000],
       [1.0, 45, 79000],
       [0.0, 44, 39000],
       [1.0, 41, 59000],
       [0.0, 42, 53000],
       [1.0, 35, 73000],
       [0.0, 41, 72000],
       [0.0, 27, 96000],
       [0.0, 30, 116000],
       [1.0, 41, 52000],
       [1.0, 41, 52000],
       [0.0, 20, 82000],
       [0.0, 46, 4100

In [13]:
y_train

array([0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,

In [14]:
X_test

array([[1.0, 36, 33000],
       [0.0, 39, 61000],
       [1.0, 36, 118000],
       [1.0, 39, 122000],
       [0.0, 26, 118000],
       [0.0, 38, 65000],
       [0.0, 20, 36000],
       [1.0, 49, 89000],
       [1.0, 31, 18000],
       [1.0, 48, 141000],
       [0.0, 34, 72000],
       [0.0, 39, 73000],
       [1.0, 35, 72000],
       [0.0, 48, 131000],
       [0.0, 53, 82000],
       [1.0, 56, 133000],
       [1.0, 60, 83000],
       [1.0, 27, 58000],
       [0.0, 28, 87000],
       [1.0, 60, 102000],
       [0.0, 40, 75000],
       [0.0, 50, 88000],
       [0.0, 44, 139000],
       [1.0, 47, 43000],
       [1.0, 45, 26000],
       [1.0, 26, 15000],
       [0.0, 58, 47000],
       [1.0, 49, 74000],
       [0.0, 53, 34000],
       [0.0, 52, 114000],
       [1.0, 39, 42000],
       [1.0, 19, 76000],
       [0.0, 18, 86000],
       [1.0, 57, 74000],
       [0.0, 27, 84000],
       [1.0, 30, 80000],
       [1.0, 22, 18000],
       [0.0, 32, 86000],
       [0.0, 50, 20000],
       [1.0, 19,

In [15]:
y_test

array([0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0])

In [16]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 1:] = sc.fit_transform(X_train[:, 1:])
X_test[:, 1:] = sc.transform(X_test[:, 1:])

In [17]:
X_train

array([[0.0, -0.8033008104771288, -1.1912179543545012],
       [0.0, 0.7569799746681295, -1.368598012704171],
       [1.0, 0.8544975237397081, 1.4399195778322673],
       [1.0, -0.5107481632623928, -1.4868513849372842],
       [1.0, -1.4859236539781793, 0.3756392277342486],
       [1.0, -1.1933710067634433, 0.5530192860839184],
       [1.0, 1.0495326218828653, -1.0434012390631098],
       [1.0, -0.21819551604765694, -0.30431766260615223],
       [1.0, 0.9520150728112867, -1.3390346696458928],
       [1.0, -1.0958534576918646, -1.072964582121388],
       [0.0, -0.5107481632623928, 1.9720597528812767],
       [1.0, 2.219743210741809, -1.0138378960048313],
       [0.0, 1.43960281816918, -1.3981613557624493],
       [0.0, 0.074357131167079, -0.39300769178098716],
       [1.0, -1.1933710067634433, 0.6417093152587533],
       [0.0, 2.0247081125986517, -0.8955845237717182],
       [1.0, 1.147050170954444, 0.5825826291421967],
       [0.0, -0.02316041790449965, 0.28694919855941375],
       [0.

In [18]:
X_test

array([[1.0, -0.12067796697607829, -1.0434012390631098],
       [0.0, 0.17187468023865762, -0.21562763343131733],
       [1.0, -0.12067796697607829, 1.4694829208905458],
       [1.0, 0.17187468023865762, 1.587736293123659],
       [0.0, -1.0958534576918646, 1.4694829208905458],
       [0.0, 0.074357131167079, -0.09737426119820415],
       [0.0, -1.6809587521213365, -0.9547112098882748],
       [1.0, 1.147050170954444, 0.6121459722004751],
       [1.0, -0.6082657123339715, -1.4868513849372842],
       [1.0, 1.0495326218828653, 2.1494398112309465],
       [0.0, -0.3157130651192356, 0.10956914020974394],
       [0.0, 0.17187468023865762, 0.13913248326802224],
       [1.0, -0.21819551604765694, 0.10956914020974394],
       [0.0, 1.0495326218828653, 1.8538063806481635],
       [0.0, 1.5371203672407585, 0.4052025707925269],
       [1.0, 1.8296730144554945, 1.9129330667647202],
       [1.0, 2.219743210741809, 0.4347659138508052],
       [1.0, -0.9983359086202861, -0.30431766260615223],
      

Logistic Regression

In [27]:
from sklearn.linear_model import LogisticRegression
logic_classifier = LogisticRegression(random_state = 0)
logic_classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

In [28]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = logic_classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[40  8]
 [ 6 26]]


0.825

KNN

In [21]:
from sklearn.neighbors import KNeighborsClassifier
knn_classifier = KNeighborsClassifier(n_neighbors = 8, metric = 'minkowski', p = 2)
knn_classifier.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=8)

In [29]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = knn_classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[40  8]
 [ 2 30]]


0.875

NAive Bayes

In [23]:
from sklearn.naive_bayes import GaussianNB
nb_classifier = GaussianNB()
nb_classifier.fit(X_train, y_train)
     

GaussianNB()

In [31]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = nb_classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[41  7]
 [ 5 27]]


0.85

SVM

In [32]:
from sklearn.svm import SVC
svm_classifier = SVC(kernel = 'linear', random_state = 0)
svm_classifier.fit(X_train, y_train)

SVC(kernel='linear', random_state=0)

In [33]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = svm_classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[42  6]
 [ 7 25]]


0.8375